version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
    depends_on:
      - auth-api
      - todos-api

  auth-api:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
    ports:
      - "8081:8081"
    depends_on:
      - users-api

  todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8082:8082"
    depends_on:
      - redis

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=8083
    ports:
      - "8083:8083"

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge